### ISSUE TITLE
Unable to rename road file

### ISSUE THREAD

**Issue by jmcaffee** [creadri/LazyRoad#1]
After renaming road file (Test1.ser to SubwayTunnel.ser), the road file is not listed in the list produced by /road
I did reload (both via the server and the client) with /reload after renaming with no difference in the list output.

After I renamed the file back to the original name it was created with (Test1.ser) and did a /reload, the road was listed as Test1

**Comment by creadri** [comment]
I've tested renaming files and works great without glitches. Are you sure you didn't copy the file or something like that?

I can't reproduce that "bug", either with /road reload or /reload command.

**Comment by wolfwoodbrbu** [comment]
Closing old fixed issues.
