### ISSUE TITLE
Roads don't exist

### ISSUE THREAD

**Issue by Ricu** [creadri/LazyRoad#7]
I installed the mod excactly like I was intended. I added the permission nodes and joined the game. But when I tried to type in /road basic for example, it just says: "There Is No Road With That Name". I checked the folder and everything and everything was at the place where it should be. I don't know, what can be the issue. Maybe it is because I am using BukkitPermission. But I don't wanna change the permissions just because of that plugin but LazyRoad is so great :) If my PermissionPlugin is the issue, is there a way to disable permissions for this plugin?
King Regards
Ricu

**Comment by creadri** [comment]
The road names are caps sensitive.
